from productManager.views.MyTokenObtainPairView import MyTokenObtainPairView
from productManager.views.ProductView import ProductView
from productManager.views.CategoryView import CategoryView
from productManager.views.ClientView import ClientView
from productManager.views.EntryOutputView import EntryOutputView
from productManager.views.HistoryEntryOutputView import HistoryEntryOutputView
