# Generated by Django 6.0.3 on 2026-03-04 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnpj', models.IntegerField()),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='EntryOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Preço unitário')),
                ('status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'BROKED'), (3, 'RETURNED')], default=1, verbose_name='Estado atual da entrada/saída')),
                ('type', models.IntegerField(choices=[(1, 'entry'), (2, 'output')], default=1, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_client', to='productManager.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Entrada e/ou Saída',
                'verbose_name_plural': 'Entradas e/ou Saídas',
            },
        ),
        migrations.CreateModel(
            name='HistoryEntryOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Preço unitário')),
                ('status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'BROKED'), (3, 'RETURNED')], default=1, verbose_name='Estado atual da entrada/saída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('entryOutput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entryOutputHistory_entryOutput', to='productManager.entryoutput', verbose_name='Entrada e/ou Saída')),
            ],
            options={
                'verbose_name': 'Histórico de Entrada e/ou Saída',
                'verbose_name_plural': 'Históricos de Entradas e/ou Saídas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Imagem')),
                ('inventory_qtd', models.IntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Valor')),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('categories', models.ManyToManyField(related_name='product_category', to='productManager.category', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AddField(
            model_name='entryoutput',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entryOutput_product', to='productManager.product', verbose_name='Produto'),
        ),
    ]
