# Generated by Django 3.2.7 on 2021-09-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='entryoutput',
            options={'verbose_name': 'Entrada e/ou Saída', 'verbose_name_plural': 'Estadas e/ou Saídas'},
        ),
        migrations.AlterModelOptions(
            name='historyentryoutput',
            options={'verbose_name': 'Histórico de Entrada e/ou Saída', 'verbose_name_plural': 'Históricos de Estadas e/ou Saídas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado em'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado em'),
        ),
        migrations.AlterField(
            model_name='entryoutput',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_client', to='productManager.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='entryoutput',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='entryoutput',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entryOutput_product', to='productManager.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='entryoutput',
            name='qtd',
            field=models.IntegerField(default=0, verbose_name='Quantitdade'),
        ),
        migrations.AlterField(
            model_name='entryoutput',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'BROKED'), (3, 'RETURNED')], default=1, verbose_name='Estado atual da entrada/saída'),
        ),
        migrations.AlterField(
            model_name='entryoutput',
            name='type',
            field=models.IntegerField(choices=[(1, 'entry'), (2, 'output')], default=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='entryoutput',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='entryoutput',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado em'),
        ),
        migrations.AlterField(
            model_name='historyentryoutput',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historyentryoutput',
            name='entryOutput',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entryOutputHistory_entryOutput', to='productManager.entryoutput', verbose_name='Entrada e/ou Saída'),
        ),
        migrations.AlterField(
            model_name='historyentryoutput',
            name='qtd',
            field=models.IntegerField(default=0, verbose_name='Quantitdade'),
        ),
        migrations.AlterField(
            model_name='historyentryoutput',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'BROKED'), (3, 'RETURNED')], default=1, verbose_name='Estado atual da entrada/saída'),
        ),
        migrations.AlterField(
            model_name='historyentryoutput',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='historyentryoutput',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado em'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='product_category', to='productManager.Category', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_qtd',
            field=models.IntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado em'),
        ),
    ]
