# Generated by Django 5.1.3 on 2024-11-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManager', '0002_auto_20210910_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryoutput',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Valor'),
        ),
    ]
